openapi: 3.0.0
info:
  title: API сервиса Lucky Insurance
  description: >-
    Коллекция запросов API сервиса. Сервис предоставляет информацию о страховках для животных
  version: 1.0.1
  contact:
    name: LuckyFilms API
    url: https://lucky.com/info
    email: LuckyFilms@lucky.com
  termsOfService: https://lucky.com/terms
  license:
    name: license 1.0.1 Lucky
    url: https://lucky.com/license
servers:
  - url: https://4453f729-1913-49be-9dcc-b7a316afa17f.mock.pstmn.io
    description: Lucky Mock
tags:
  - name: Insurance Server API
paths:
  /insurance:
    get:
      tags:
        - Insurance Server API
      summary: Описание всех страховок для животных
      description: Просмотр всего списка страховок для животных
      operationId: insuranceList
      responses:
        '200':
          description: список страховок
          content:
            application/json:
              schema:
                properties:
                  description:
                    type: string
                    description: перечень преимуществ
                    example: Помощь ветеринара 24/7. Онлайн консультации. Большой выбор ветклиник.
                  insurances:
                    type: array
                    items:
                          $ref: '#/components/schemas/response_200'
        '400':
          description: bad input parameter
        '404':
          description: not found
        '500':
          description: internal server error
        '502':
          description: bad gateway
components:
  schemas:
    response_200:
      required:
        - type
        - details
        - price
        - currency
        - period
      type: object 
      properties:
        type: 
          type: string
          description: тип питомца
          example: собака
        details:
          type: string
          description: описание условий страхования
          example: Круглосуточные консультации ветеринарного врача по телефону, в чате или видеосвязи. Включена ежегодная вакцинация от бешенства.
        price:
          type: integer
          description: стоимость
          example: 50000
        currency:
          type: string
          description: вид валюты
          example: 'рублей'
        period:
          type: string
          description: период оплаты
          example: 'в год'